### ISSUE TITLE
TopologyException error in mapr

### ISSUE THREAD

**Issue by VirginiaMorera** [jamesgrecian/mapr#2]
Hey James, 

Super useful function, thanks!! I've found a small issue that is easily fixed: line 73 throws the following error for the Northern hemisphere: 

` Evaluation error: TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point 78.719726562500085 31.887646484374983 at 78.719726562500085 31.887646484374983.`

I've managed to fix that by wraping `world_shp` in an `st_buffer`, so it looks like this: 
`world_shp <- sf::st_crop(st_buffer(world_shp, 0), CP)` 
which should not alter the resulting map. 

In addition, may I suggest adding a `segm` argument to the function, so the user can select the length of the segments in the `st_segmentize` of line 81? for smaller (or more zoomed in) maps, or if they are not intended to be used to create a mesh, it might be interesting to have a smaller value there!

**Comment by jamesgrecian** [comment]
Thanks @VirginiaMorera. Not sure why that error has arisen. I've applied the fix you suggested and updated the package.
